version: "3.8"
services:
    mysqldb:
        environment:
            MYSQL_DATABASE: expense
            MYSQL_ROOT_PASSWORD: admin
        image: mysql
        ports:
            - "3308:3306"
        restart: always
        volumes:
            - db-config:/etc/mysql
            - db-data:/var/lib/mysql
    # backend: 
    #     image: 976325135345.dkr.ecr.us-west-1.amazonaws.com/expense-backend:latest
    #     ports: 
    #         - "3000:3000"
    #     depends_on:
    #         - mysqldb
volumes:
    db-config:
    db-data:

